import "./globals.css";
import { Montserrat } from "next/font/google";
import "./layout2.css";

import { Footer } from "@/modules/footer";

import { Header } from "@/modules/header";
import "./footer2.css";
import Head from "next/head";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-black">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
